spring.application.name=backend

# 1. TELL SPRING TO LOAD THE HIDDEN SECRET FILE
spring.profiles.include=secret

# 2. DATABASE (Using variables with fallbacks)
spring.datasource.url=jdbc:postgresql://localhost:5433/blog_db
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin123**}

# 3. HIBERNATE SETTINGS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. GOOGLE OAUTH2 (Strictly variables, no fallbacks!)
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

# 5. GITHUB OAUTH2 (Strictly variables, no fallbacks!)
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=user:email,read:user